rules:
  class-name-format: 0
  nesting-depth:
    - 1
    - max-depth: 4
  no-duplicate-properties: 0
  no-ids: 0
  no-important: 0
  no-url-domains: 0
  no-url-protocols: 0
  no-vendor-prefixes: 0
  property-sort-order: 0
